apiVersion: v1
kind: Secret
metadata:
  name: harish-postgresql
  namespace: default
  labels:
    app: harish-postgresql
type: Opaque
data:
  postgresql-password: NjA5Y2FiZTI2YTFjYjBmOGI2ODg5MmY3Mzk1ZTg4NGM3MGJjNmNjNjAxOTNmMTRhZGNhNzZlZjQwZjhk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harish-postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harish-postgresql
  template:
    metadata:
      labels:
        app: harish-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:16.4
          env:
            - name: POSTGRES_USER
              value: harish
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harish-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: harish-postgresql
  namespace: default
spec:
  selector:
    app: harish-postgresql
  ports:
    - port: 5432
